version: "3.8"
services:
  minio:
    image: quay.io/minio/minio:latest
    network_mode: bridge
    restart: always
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    expose:
      - 9000
      - 9090
    volumes:
      - miniodata:/data
    command: server /miniodata --console-address :9090
    ports:
      - "9000:9000"
      - "9090:9090"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  database:
    image: postgres:alpine
    restart: always
    network_mode: bridge
    expose:
      - 3032
    ports:
      - "3032:5432"
    volumes:
      - mediadata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=media_service
  app:
    build: .
    restart: always
    network_mode: bridge
    container_name: media_service
    expose:
      - 3000
      - 3001
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - database
      - minio
    links:
      - database
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/media_service
      MINIO_URL: http://minio:9000
volumes:
  mediadata:
  miniodata: