version: '3.7'

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-05-18T00-05-36Z
    command: server --console-address ":9090" /miniodata
    expose:
      - "9000"
      - "9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio
    volumes:
      - miniodata:/data
  nginx:
    image: nginx:1.24-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9090:9090"
    depends_on:
      - minio
  database:
    image: postgres:alpine
    restart: always
    expose:
      - 3032
    ports:
      - "3032:5432"
    volumes:
      - mediadata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=media_service
  app:
    build: .
    restart: always
    container_name: media_service
    expose:
      - 3000
      - 3001
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - database
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/media_service
      MINIO_URL: http://minio:9000

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  miniodata:
  mediadata:
